# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'  # ou a versão do .NET que você está utilizando
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: |
    dotnet build --configuration Release
  displayName: 'Build project'
- script: |
    dotnet test --configuration Release
  displayName: 'Run tests'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureSubscription'
    appName: 'aspnet-app-service'
    package: $(Build.ArtifactStagingDirectory)//*.zip