name: CI/CD Pipeline


on:
  push:
branches:
- main


jobs:
  build:
runs-on: ubuntu-latest
steps:
name: Checkout code
  uses: actions/checkout@v2
name: Setup .NET
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '5.x' # ou a versão do .NET que você está utilizando
name: Build project
  run: dotnet build --configuration Release
name: Run tests
  run: dotnet test --configuration Release


  deploy:
runs-on: ubuntu-latest
needs: build
steps:
name: Checkout code
  uses: actions/checkout@v2
name: Setup .NET
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '5.x' # ou a versão do .NET que você está utilizando
name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v2
  with:
    app-name: 'aspnet-app-service' # Nome do seu App Service
    slot-name: 'production'
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
`
